name: lineker
description: Access links between your devices in real time!

publish_to: "none"

version: 2.2.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.9
  firebase_core: ^1.10.2
  firebase_auth: ^3.3.0
  google_sign_in: ^5.2.1
  firebase_database: ^8.2.0
  url_launcher: ^6.0.17
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  share_plus: ^3.0.4
  screenshot: ^1.2.3
  path_provider: ^2.0.8
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.3.0
  qr_code_scanner: ^0.6.1
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.2
  google_mobile_ads: ^1.2.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/Lineker Logo.png
    - assets/images/Drawer.png
